In [1]:
my_list=[1,2,3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [4]:
arr=np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]

In [7]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [17]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [21]:
np.linspace(0,5,10)   #10 different integer between 0 and 5

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [22]:
np.linspace(0,10,20)    #20 different integers between 0 and 10

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [23]:
np.eye(4)   #identity square metrix of size 4x4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
np.random.rand(5)

array([0.69171446, 0.04194404, 0.20410004, 0.28046506, 0.23247487])

In [26]:
np.random.rand(3,3)

array([[0.6962728 , 0.37328847, 0.19465016],
       [0.2224742 , 0.75742408, 0.19002423],
       [0.06003584, 0.88251191, 0.67033588]])

In [29]:
np.random.randn(5)

array([ 0.0422774 ,  0.84410131,  0.91629183, -0.75072093, -0.50255575])

In [30]:
np.random.randn(4,3)

array([[ 2.26938570e-01,  1.02497428e+00,  1.77320298e+00],
       [-6.27222832e-01, -3.75354883e-01,  1.15227140e+00],
       [-3.10494432e-01, -6.39483016e-01,  3.83026836e-01],
       [-2.18117977e+00,  3.75030356e-01, -9.98488935e-04]])

In [34]:
np.random.randint(1,100)   #including 1 and excluding 100

84

In [35]:
np.random.randint(1,100,10)   #10 random integers ranging from 1 to 100

array([79, 13, 15, 66, 75, 40, 16, 40,  5, 47])

In [36]:
arr=np.arange(25)

In [37]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [64]:
ranarr=np.random.randint(0,50,10) #10 integers between  and 50

In [65]:
ranarr

array([ 9, 28, 41, 16, 20, 47, 19, 23, 40, 26])

In [40]:
newarr=arr.reshape(5,5)

In [63]:
ran=np.random.randint(50,100)   #an integer between 50 and 100
ran

80

In [41]:
newarr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [43]:
newarr2=arr.reshape(5,10)   #rows * matrix = size of array

ValueError: cannot reshape array of size 25 into shape (5,10)

In [44]:
ranarr

array([35, 48,  1,  6, 17, 13, 10, 40, 32, 17])

In [50]:
ranarr.max()   #max value in numpy array

48

In [51]:
ranarr.min()   #min value in numpy array

1

In [52]:
ranarr

array([35, 48,  1,  6, 17, 13, 10, 40, 32, 17])

In [53]:
ranarr.argmax()   #index of max number in array

1

In [54]:
ranarr.argmin()   #index of min value in array

2

In [55]:
ranarr.shape

(10,)

In [56]:
newarr.shape

(5, 5)

In [57]:
arr.dtype

dtype('int32')

In [58]:
x=np.random.randn(4)

In [59]:
x

array([-1.4951138 ,  2.74373721,  0.67361561,  0.18493655])

In [60]:
x.dtype

dtype('float64')