In [1]:
import numpy as np

In [2]:
arr=np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[5]

5

In [5]:
arr[3:8]

array([3, 4, 5, 6, 7])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [9]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [10]:
arr[0:8:2]

array([0, 2, 4, 6])

In [11]:
arr[0:5]=55

In [12]:
arr

array([55, 55, 55, 55, 55,  5,  6,  7,  8,  9, 10])

In [13]:
arr=np.arange(0,11)

In [14]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
slice_arr=arr[0:6]

In [18]:
slice_arr

array([0, 1, 2, 3, 4, 5])

In [23]:
slice_arr[:]=99   #change the value in real array 'arr'

In [24]:
slice_arr

array([99, 99, 99, 99, 99, 99])

In [26]:
arr   #values change due to slice_arr[:]=99

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [27]:
newa=arr.copy()   #create a new array

In [28]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [29]:
newa

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [30]:
newa[:]=100   #change in newa not in arr

In [31]:
newa

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [32]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [33]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])

In [34]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [35]:
arr_2d[0][0]

5

In [36]:
arr_2d[0,0]

5

In [38]:
arr_2d[0]

array([ 5, 10, 15])

In [40]:
arr_2d[1][2]

30

In [41]:
arr_2d[1,2]

30

In [42]:
arr_2d[1:,1:]

array([[25, 30],
       [40, 45]])

In [43]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [49]:
arr_2d[1:,1:]

array([[25, 30],
       [40, 45]])

In [67]:
arr=np.arange(1,11)

In [68]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
bool_arr=arr>5

In [70]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [71]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [73]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [74]:
arr[arr<3]

array([1, 2])

In [75]:
arr_2d=np.arange(50).reshape(5,10)

In [76]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [77]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])